---
# TODO: должен быть выбор версии php
- name: setup apache vhost
  include_role:
    name: apache
  vars:
    apache_vhosts:
      - servername: "{{ site_domain }}"
        serveralias: "www.{{ site_domain }} {{ site_domain_test }}"
        documentroot: "{{ site_root }}"
