---
# TODO: должен быть выбор версии php
- name: setup apache vhost
  include_role:
    name: apache-vhosts
  vars:
    apache_vhosts_sites:
      "{{ site_domain }}":
        servername: "{{ site_domain }}"
        serveralias: "www.{{ site_domain }} {{ site_domain_test }}"
        documentroot: "{{ site_root }}"
        extra_parameters: |
          ProxyPassMatch "^/(.*\.php(/.*)?)$" "unix:{{ site_php_socket }}|fcgi://localhost:9000{{ site_root }}"
