- name: Cron scripts directory
  file: path="{{ site_homedir }}/cron"
        state=directory
        owner={{ site_user }}
        group={{ site_user }}
  tags: [ site, cron ]

- name: Cron jobs
  cron:
    user="{{ site_user }}"
    name="{{ item.name }}"

    weekday="{{ item.weekday|default ('*') }}"
    day="{{ item.day|default ('*') }}"
    hour="{{ item.hour|default ('*') }}"
    minute="{{ item.minute|default ('*') }}"

    job="{{ item.job }}"
    state=present
  with_items: site_cronjobs
  when: site_cronjobs is defined
  tags: [ site, cron ]
