---

- name: "{{ site_domain}} : Register site_dns_domain if not defined"
  set_fact:
    site_dns_domain: "{{ site_domain }}"
  when: site_dns_domain is not defined

- name: "{{ site_domain}} : Check domain exists in Selectel"
  local_action: "shell selectel-dns getDomainByName domain_name={{ site_dns_domain }} | grep -c 'create_date'"
  register: site_dns_selectel_exists
  failed_when: false
  changed_when: false

- name: "{{ site_domain}} : Create zone.hosts file"
  local_action:
    module: template
    src: templates/bind/default.hosts.j2
    dest: /tmp/site-bind-zone.hosts
  when: site_dns_selectel_exists.stdout == '0'

- name: "{{ site_domain}} : Add domain to Selectel"
  local_action: "command selectel-dns addDomain name=={{ site_dns_domain }} bind_zone==/tmp/site-bind-zone.hosts"
  when: site_dns_selectel_exists.stdout == '0'
