---
- name: Load site variables
  include_vars: "{{ vars_file }}"
  tags: [ site, always ]

- include: user.yml
- include: apache2.yml
- include: nginx.yml
- include: dns.yml
- include: mysql.yml
- include: cron.yml
- include: engine.yml
