---
- name: Load site variables
  include_vars: "{{ site_vars_file }}"
  tags: [ site, always ]

- include: user.yml
  tags: [ site, user ]

#- include: apache.yml
#- include: nginx.yml
#- include: dns.yml

#- include: mysql.yml
#  when: site_mysql_host is defined and site_mysql_db is defined and site_mysql_user is defined and site_mysql_password is defined

#- include: cron.yml

#- include: sync.yml
#  when: site_sync_files

#- include: sync_mysql.yml
#  when: site_sync_mysql

#- include: engine.yml
