---
- name: Load site variables
  include_vars: "{{ vars_file }}"
  tags: [ site, always ]

- include: user.yml
- include: apache2.yml
- include: nginx.yml
- include: dns.yml
- include: mysql.yml
- include: cron.yml

- include: sync.yml
  when: site_sync_files

- include: sync_mysql.yml
  when: site_sync_mysql

- include: engine.yml
