---
- name: Load site variables
  include_vars: "{{ site_vars_file }}"
  tags: [ site, always ]

- include: user.yml
  tags: [ site, user ]

- include: nginx.yml
  tags: [ site, nginx, nginx-vhosts ]

- include: php.yml
  tags: [ site, php ]

- include: apache.yml
  tags: [ site, apache, apache_vhosts ]

- include: mysql.yml
  when: site_mysql_host is defined and site_mysql_user is defined and site_mysql_password is defined
  tags: [ site, mysql ]

- include: cron.yml
  tags: [ site, cron ]

- name: Check if user Debian-exim exists
  shell: getent passwd Debian-exim | wc -l
  register: site_register_exim4_exists
  changed_when: false
  tags: [ site, exim4 ]

- include: exim4.yml
  when: site_register_exim4_exists.stdout == '1' and site_exim4_dkim_private
  tags: [ site, exim4 ]

#- include: dns.yml
#  tags: [ site, dns ]

- include: sync_files.yml
  when: site_sync_files
  tags: [ site, sync, sync_files ]

- include: sync_mysql.yml
  when: site_sync_mysql
  tags: [ site, sync, sync_mysql ]

- include: site_config.yml
  tags: [ site, sync_mysql, drupal, config ]

- name: Site information
  debug:
    msg:
      - "************************************"
      - "          Site information          "
      - "************************************"
      - " domain:     http://{{ site_domain }}"
      - "{% if site_domains_secondary %} secondary:  http://{{ site_domains_secondary | join(', http://') }}{% endif %}"
      - " sftp user:  {{ site_user }}"
      - " mysql db:   {{ site_mysql_db }}"
      - " mysql pass: {{ site_mysql_password }}"
      - "************************************"
  tags: always, skip_ansible_lint