---
- name: Load site variables
  include_vars: "{{ site_vars_file }}"
  tags: [ site, always ]

- include_tasks: user.yml
  tags: [ site, user ]

- include_tasks: nginx_deprecations.yml
  when: site_nginx_template and site_nginx_template in ['default', 'default_https', 'drupal', 'drupal_https', 'joomla']
  tags: [ site, nginx, php ]

#- name: Register www domains remove
#  set_fact:
#    site_domains_remove: [ "{{ site_domain}}" ]
#  when: "'www' in site_domain"
#  tags: [ site, apache, nginx ]

- include_tasks: nginx.yml
  tags: [ site, nginx, nginx-vhosts ]

- include_tasks: php.yml
  tags: [ site, php ]

- include_tasks: apache.yml
  tags: [ site, apache, apache_vhosts ]

- include_tasks: mysql.yml
  when: site_mysql_host is defined and site_mysql_user is defined and site_mysql_password is defined
  tags: [ site, mysql ]

- include_tasks: cron.yml
  tags: [ site, cron ]

- name: "{{ site_domain}} : Check if user Debian-exim exists"
  shell: getent passwd Debian-exim | wc -l
  register: site_register_exim4_exists
  changed_when: False
  tags: [ site, exim4 ]

- include_tasks: exim4.yml
  when: site_register_exim4_exists.stdout == '1' and site_exim4_dkim_private
  tags: [ site, exim4 ]

- name: Check that running all tasks
  command: /bin/true
  changed_when: False
  register: site_register_running_all

- include_tasks: dns.yml
  tags: [ site, dns ]
  when: site_dns_domains is defined and site_register_running_all is not defined

- include_tasks: drupal.yml
  tags: [ site, engine, drupal ]
  when: site_install_engine is defined and site_install_engine == 'drupal'

- include_tasks: solr.yml
  tags: [ site, solr ]
  when: site_solr

- include_tasks: sync_files.yml
  when: site_sync_files
  tags: [ site, sync, sync_files ]

- include_tasks: sync_mysql.yml
  when: site_sync_mysql
  tags: [ site, sync, sync_mysql ]

- include_tasks: site_config.yml
  tags: [ site, sync, sync_mysql, drupal, config ]

- name: "{{ site_domain}} : Site information"
  debug:
    msg:
      - "************************************"
      - "          Site information          "
      - "************************************"
      - " domain:     http{% if site_ssl %}s{% endif %}://{{ site_domain }}"
      - "{% if site_domains_secondary %} secondary:  http{% if site_ssl %}s{% endif %}://{{ site_domains_secondary | join(', http://') }}{% endif %}"
      - " sftp user:  {{ site_user }}"
      - "{% if site_mysql_db is defined %} mysql db:   {{ site_mysql_db }}{% endif %}"
      - "{% if site_mysql_password is defined %} mysql pass: {{ site_mysql_password }}{% endif %}"
      - " site root:  {{ site_root }}"
      - " server IP:  {{ site_dns_ip }}"
      - "************************************"
  when: site_user is defined
  tags: always, skip_ansible_lint, print_action

- name: "{{ site_domain}} : Drupal information"
  debug:
    msg:
      - "{{ site_domain }} - {{ drupal_account_name }}"
      - "{{ drupal_account_pass }}"
      - "{% if drupal_drs_add_users is defined and drupal_drs_add_users | changed and drupal_drs_add_users.stdout_lines is defined %}{{ drupal_drs_add_users.stdout_lines }}{% endif %}"
      - "{% if drupal_drs_add_users is defined and drupal_drs_add_users | changed and drupal_drs_add_users.stderr_lines is defined %}{{ drupal_drs_add_users.stderr_lines }}{% endif %}"
  when: drupal_site_installed is defined and ('Drupal bootstrap' not in drupal_site_installed.stdout)
  tags: drupal, skip_ansible_lint, print_action

- name: "{{ site_domain}} : Solr information"
  debug:
    msg:
      - " Solr web:  http://{{ site_solr_domain }}"
      - " Solr host: {{ site_solr_domain }}"
      - " Solr port: 80"
      - " Solr path: /solr/{{ site_solr_core_name }}"
      - "{% if site_solr_basic_auth %} Solr using basic auth, login and password in site yml config, site_solr_basic_auth{% endif %}"
  when: site_solr
  tags: solr, skip_ansible_lint, print_action
