---
- name: Check for old site_nginx_template
  debug: msg="site_nginx_template must be replaced to site_nginx_engine"
  failed_when: true
  ignore_errors: yes

- name: Define legacy site_nginx_template mapping
  set_fact:
    site_nginx_engine_mapping:
      default:
        engine: default
        ssl: no
      default_https:
        engine: default
        ssl: yes
      drupal:
        engine: drupal
        ssl: no
      drupal_https:
        engine: drupal
        ssl: yes
      joomla:
        engine: joomla
        ssl: no

- name: Define site_nginx_engine
  set_fact:
    site_nginx_engine: "{{ site_nginx_engine_mapping[site_nginx_template]['engine'] }}"
    site_ssl: "{{ site_nginx_engine_mapping[site_nginx_template]['ssl'] }}"
    site_nginx_template: ''
