---
- name: Get public key of remote server
  command: ssh-keyscan -H "{{ site_src_host }}"
  register: site_src_host_key
  tags: [ site, sync, files ]
  changed_when: no

- debug: var=site_src_host_key.stdout
  tags: [ site, sync, files ]

- name: Ensure host known
  known_hosts:
    name="{{ site_src_host }}"
    key="{{ site_src_host_key.stdout }}"
    state=present
  tags: [ site, sync, files ]

- name: Sync main files
  command: |
    rsync --archive --delete \
    "{{ site_src_user }}@{{ site_src_host }}:{{ site_src_path }}/" \
    "{{ site_root }}"
  when: site_src_user and site_src_host and site_src_path
  tags: [ site, sync, files ]
