---

# http://serverfault.com/questions/416787/nginx-403-forbidden-error-hosting-in-user-home-directory
- name: Ensure user directory parent exists
  file: path="/home/{{ site_user }}"
        state=directory
        mode=701
  tags: [ site, user ]

- name: User add
  user:
    name={{ site_user }}
    home={{ site_homedir }}
    shell=/bin/zsh
  tags: [ site, user ]

- name: User directory parent access
  file: path="/home/{{ site_user }}"
        owner={{ site_user }}
        group={{ site_user }}
  tags: [ site, user ]

- name: User directory access
  file: path="{{ site_homedir }}"
        state=directory
        mode=751
        owner={{ site_user }}
        group={{ site_user }}
  tags: [ site, user ]

# ssh access
- name: Add ssh public keys to user
  authorized_key:
    user={{ site_user }}
    key="{{ lookup('file', item) }}"
  with_fileglob:
    - "../../../vars/{{ ssh_public_keys_dir }}/*" # TODO: ../../../vars is hack
  tags: [ site, user, ssh ]

- name: Remove old ssh public keys from user
  authorized_key:
    user={{ site_user }}
    key="{{ lookup('file', item) }}"
    state=absent
  with_fileglob:
    - "../../../vars/{{ ssh_public_keys_removed_dir }}/*"
  tags: [ site, user, ssh ]

- name: User directories
  file: path={{ item }}
        state=directory
        owner={{ site_user }}
        group={{ site_user }}
  with_items:
    - "{{ site_homedir }}/etc"
    - "{{ site_wwwdir }}"
    - "{{ site_root }}"
  tags: [ site, user ]
