---
- name: User add
  user:
    name: "{{ site_user }}"
    home: "{{ site_homedir }}"
  tags: user_create

- name: User directory access
  file:
    path: "{{ site_homedir }}"
    state: directory
    mode: 0750
    owner: "{{ site_user }}"
    group: "{{ site_nginx_user }}"
  tags: [ user_create, permissions ]

- name: User directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ site_user }}"
    group: "{{ site_user }}"
  with_items:
    - "{{ site_homedir }}/etc"
    - "{{ site_homedir }}/run"
    - "{{ site_wwwdir }}"
    - "{{ site_root }}"
  tags: [ user_create, permissions ]

- name: setup git
  include_role:
    name: git
  vars:
    git_user: "{{ site_user }}"
  tags: git
  when: site_setup_git

- name: setup ssh-keys
  include_role:
    name: ssh-keys
  vars:
    ssh_keys_user: "{{ site_user }}"
  tags: ssh-keys
  when: site_setup_ssh_keys

- name: setup vim
  include_role:
    name: vim
  vars:
    vim_user: "{{ site_user }}"
  tags: vim
  when: site_setup_vim

- name: setup zsh
  include_role:
    name: zsh
  vars:
    zsh_user: "{{ site_user }}"
  tags: zsh
  when: site_setup_zsh
